-- master 初始化:创建复制用户 + 测试库
CREATE USER 'repl'@'%' IDENTIFIED BY 'repl123';
GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'repl'@'%';
FLUSH PRIVILEGES;
CREATE DATABASE IF NOT EXISTS apartment_ha_demo DEFAULT CHARSET utf8mb4;
